// Package storage stores file content by opaque key. Keys are generated by the server
// (never derived from client input), so no path traversal is possible.
package storage

import (
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Backend is the storage abstraction, so other backends (e.g. S3-compatible) can be added.
// Only the local filesystem implementation ships today.
type Backend interface {
	// OpenAppend opens (creating if needed) an in-progress upload for appending at offset.
	// Content past offset is truncated, which reconciles crashes between write and DB update.
	OpenAppend(key string, offset int64) (io.WriteCloser, error)
	OpenRead(key string) (ReadSeekCloser, int64, time.Time, error)
	// Commit atomically moves a finished upload to its permanent key.
	Commit(uploadKey, blobKey string) error
	Remove(key string) error
	Healthy() error
	// Walk lists stored keys under prefix with their modification time (used by orphan cleanup).
	Walk(prefix string, fn func(key string, mod time.Time)) error
	LocalPath(key string) (string, bool)
	Usage() (total, free uint64, ok bool)
}

type ReadSeekCloser interface {
	io.ReadSeeker
	io.Closer
}

var (
	ErrNotFound    = errors.New("file not found in storage")
	ErrUnavailable = errors.New("storage backend unavailable")
)

const sentinel = ".ferry-storage"

type Local struct{ root string }

func NewLocal(root string) (*Local, error) {
	abs, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}
	for _, d := range []string{"uploads", "blobs"} {
		if err := os.MkdirAll(filepath.Join(abs, d), 0o750); err != nil {
			return nil, fmt.Errorf("create storage directory: %w", err)
		}
	}
	if err := os.WriteFile(filepath.Join(abs, sentinel), []byte("ferry storage root\n"), 0o640); err != nil {
		return nil, fmt.Errorf("storage is not writable: %w", err)
	}
	return &Local{root: abs}, nil
}

func (l *Local) path(key string) string {
	// Keys are "uploads/<id>" or "blobs/<id>"; blobs are fanned out by the first two characters.
	if strings.HasPrefix(key, "blobs/") && len(key) > 8 {
		id := key[len("blobs/"):]
		return filepath.Join(l.root, "blobs", id[:2], id)
	}
	return filepath.Join(l.root, filepath.FromSlash(key))
}

func (l *Local) LocalPath(key string) (string, bool) { return l.path(key), true }

func (l *Local) classify(err error) error {
	if errors.Is(err, fs.ErrNotExist) {
		if l.Healthy() != nil {
			return ErrUnavailable
		}
		return ErrNotFound
	}
	return err
}

func (l *Local) OpenAppend(key string, offset int64) (io.WriteCloser, error) {
	f, err := os.OpenFile(l.path(key), os.O_CREATE|os.O_WRONLY, 0o640)
	if err != nil {
		return nil, l.classify(err)
	}
	st, err := f.Stat()
	if err != nil {
		f.Close()
		return nil, err
	}
	if st.Size() < offset {
		f.Close()
		return nil, fmt.Errorf("upload data is shorter than recorded offset (%d < %d)", st.Size(), offset)
	}
	if st.Size() > offset {
		if err := f.Truncate(offset); err != nil {
			f.Close()
			return nil, err
		}
	}
	if _, err := f.Seek(offset, io.SeekStart); err != nil {
		f.Close()
		return nil, err
	}
	return f, nil
}

func (l *Local) OpenRead(key string) (ReadSeekCloser, int64, time.Time, error) {
	f, err := os.Open(l.path(key))
	if err != nil {
		return nil, 0, time.Time{}, l.classify(err)
	}
	st, err := f.Stat()
	if err != nil {
		f.Close()
		return nil, 0, time.Time{}, err
	}
	return f, st.Size(), st.ModTime(), nil
}

func (l *Local) Commit(uploadKey, blobKey string) error {
	dst := l.path(blobKey)
	if err := os.MkdirAll(filepath.Dir(dst), 0o750); err != nil {
		return err
	}
	return l.classify(os.Rename(l.path(uploadKey), dst))
}

func (l *Local) Remove(key string) error {
	err := os.Remove(l.path(key))
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	return err
}

func (l *Local) Healthy() error {
	if _, err := os.Stat(filepath.Join(l.root, sentinel)); err != nil {
		return ErrUnavailable
	}
	return nil
}

func (l *Local) Walk(prefix string, fn func(key string, mod time.Time)) error {
	base := filepath.Join(l.root, prefix)
	return filepath.WalkDir(base, func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		info, err := d.Info()
		if err != nil {
			return nil
		}
		fn(prefix+"/"+d.Name(), info.ModTime())
		return nil
	})
}

func (l *Local) Usage() (total, free uint64, ok bool) { return diskUsage(l.root) }
